version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - NODE_ENV=production
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
    volumes:
      - tmp-uploads:/tmp/uploads
    expose:
      - 3000

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - API_URL=http://backend:3000
    ports:
      - 3200:80
    depends_on:
      - backend

volumes:
  tmp-uploads: